// Restaurant + menu data with bilingual (ko/en) names, descriptions, and toppings.
// Topping labels keep the original "+XXX원" price marker so the existing parser still works.

export const restaurants = [
  {
    id: 1,
    name: { ko: "한입치킨 강남점", en: "OneBite Chicken — Gangnam" },
    emoji: "🍗", time: "25~35", rating: 4.9, reviews: 2847, fee: 2500,
    category: { ko: "치킨", en: "Chicken" },
    badge: { ko: "인기", en: "Popular" },
    menus: [
      { id: "c1",
        name: { ko: "크리스피 반반치킨", en: "Half & Half Crispy Chicken" },
        desc: { ko: "후라이드 + 양념 반반", en: "Half fried, half sweet & spicy" },
        price: 21900,
        options: { spicy: true, size: true, toppings: [
          { ko: "치즈소스 추가+1000원", en: "Add cheese sauce+1000원" },
          { ko: "콜라 추가+1500원", en: "Add cola+1500원" },
        ] } },
      { id: "c2",
        name: { ko: "순살 간장치킨", en: "Boneless Soy-Glazed Chicken" },
        desc: { ko: "달콤짭짤 시그니처", en: "Signature sweet-savory glaze" },
        price: 19900,
        options: { spicy: true, toppings: [
          { ko: "치즈소스 추가+1000원", en: "Add cheese sauce+1000원" },
          { ko: "콜라 추가+1500원", en: "Add cola+1500원" },
        ] } },
      { id: "c3",
        name: { ko: "치즈볼 5개", en: "Cheese Balls (5pc)" },
        desc: { ko: "바삭 쫄깃 사이드", en: "Crispy-chewy side bites" },
        price: 4500, options: {} },
    ],
  },
  {
    id: 2,
    name: { ko: "도쿄라멘 스테이션", en: "Tokyo Ramen Station" },
    emoji: "🍜", time: "18~28", rating: 4.8, reviews: 1523, fee: 3200,
    category: { ko: "일식", en: "Japanese" },
    badge: { ko: "추천", en: "Recommended" },
    menus: [
      { id: "r1",
        name: { ko: "돈코츠 라멘", en: "Tonkotsu Ramen" },
        desc: { ko: "진한 사골 육수 12시간", en: "Pork-bone broth simmered 12 hours" },
        price: 11000,
        options: { spicy: true, toppings: [
          { ko: "차슈 추가+2000원", en: "Add chashu+2000원" },
          { ko: "반숙달걀 추가+1000원", en: "Add soft egg+1000원" },
          { ko: "대파 추가+500원", en: "Add scallion+500원" },
        ] } },
      { id: "r2",
        name: { ko: "매운 미소 라멘", en: "Spicy Miso Ramen" },
        desc: { ko: "얼큰한 된장 베이스", en: "Bold spicy miso base" },
        price: 12000,
        options: { spicy: true, toppings: [
          { ko: "차슈 추가+2000원", en: "Add chashu+2000원" },
          { ko: "반숙달걀 추가+1000원", en: "Add soft egg+1000원" },
        ] } },
      { id: "r3",
        name: { ko: "카라아게", en: "Karaage" },
        desc: { ko: "바삭한 닭튀김 6조각", en: "Crispy fried chicken — 6 pieces" },
        price: 6500, options: { spicy: true } },
    ],
  },
  {
    id: 3,
    name: { ko: "파스타랩 성수키친", en: "PastaLab — Seongsu Kitchen" },
    emoji: "🍝", time: "30~40", rating: 4.7, reviews: 983, fee: 2800,
    category: { ko: "양식", en: "Italian" },
    badge: { ko: "", en: "" },
    menus: [
      { id: "p1",
        name: { ko: "새우 로제 파스타", en: "Shrimp Rosé Pasta" },
        desc: { ko: "부드러운 로제소스", en: "Creamy tomato-cream sauce" },
        price: 14900,
        options: { spicy: true, size: true, toppings: [
          { ko: "새우 추가+2500원", en: "Add shrimp+2500원" },
          { ko: "치즈 추가+1000원", en: "Add cheese+1000원" },
        ] } },
      { id: "p2",
        name: { ko: "봉골레 오일 파스타", en: "Vongole Oil Pasta" },
        desc: { ko: "깔끔한 바지락 감칠맛", en: "Clean clam umami" },
        price: 13900,
        options: { size: true, toppings: [
          { ko: "바지락 추가+2000원", en: "Add clams+2000원" },
          { ko: "치즈 추가+1000원", en: "Add cheese+1000원" },
        ] } },
      { id: "p3",
        name: { ko: "갈릭 브레드", en: "Garlic Bread" },
        desc: { ko: "버터 갈릭 토스트", en: "Buttery garlic toast" },
        price: 3900, options: {} },
    ],
  },
  {
    id: 4,
    name: { ko: "그린포케 하우스", en: "GreenPoke House" },
    emoji: "🥗", time: "15~25", rating: 4.9, reviews: 1205, fee: 1800,
    category: { ko: "샐러드", en: "Salad" },
    badge: { ko: "신규", en: "New" },
    menus: [
      { id: "g1",
        name: { ko: "연어 포케볼", en: "Salmon Poke Bowl" },
        desc: { ko: "신선한 연어와 아보카도", en: "Fresh salmon with avocado" },
        price: 13500,
        options: { size: true, toppings: [
          { ko: "연어 추가+3000원", en: "Add salmon+3000원" },
          { ko: "아보카도 추가+1500원", en: "Add avocado+1500원" },
          { ko: "드레싱 추가+500원", en: "Extra dressing+500원" },
        ] } },
      { id: "g2",
        name: { ko: "닭가슴살 포케볼", en: "Chicken Breast Poke Bowl" },
        desc: { ko: "단백질 든든 한끼", en: "High-protein bowl" },
        price: 11900,
        options: { size: true, toppings: [
          { ko: "닭가슴살 추가+2000원", en: "Add chicken+2000원" },
          { ko: "드레싱 추가+500원", en: "Extra dressing+500원" },
        ] } },
      { id: "g3",
        name: { ko: "망고 요거트", en: "Mango Yogurt" },
        desc: { ko: "상큼한 디저트", en: "Bright, fresh dessert" },
        price: 4900, options: {} },
    ],
  },
  {
    id: 5,
    name: { ko: "엄마손 한식당", en: "Mom's Hand Korean Kitchen" },
    emoji: "🍚", time: "20~30", rating: 4.8, reviews: 3102, fee: 2000,
    category: { ko: "한식", en: "Korean" },
    badge: { ko: "인기", en: "Popular" },
    menus: [
      { id: "h1",
        name: { ko: "김치찌개", en: "Kimchi Stew" },
        desc: { ko: "묵은지로 끓인 깊은 맛", en: "Aged kimchi, deep flavor" },
        price: 9500,
        options: { spicy: true, toppings: [
          { ko: "공기밥 추가+1000원", en: "Add rice+1000원" },
          { ko: "두부 추가+500원", en: "Add tofu+500원" },
        ] } },
      { id: "h2",
        name: { ko: "돌솥비빔밥", en: "Stone-Pot Bibimbap" },
        desc: { ko: "누룽지까지 바삭하게", en: "Crispy rice crust included" },
        price: 11000,
        options: { spicy: true, toppings: [
          { ko: "달걀 추가+500원", en: "Add egg+500원" },
          { ko: "공기밥 추가+1000원", en: "Add rice+1000원" },
        ] } },
      { id: "h3",
        name: { ko: "제육볶음 정식", en: "Spicy Pork Set" },
        desc: { ko: "매콤달콤 밥도둑", en: "Sweet-spicy rice killer" },
        price: 12000,
        options: { spicy: true, toppings: [
          { ko: "공기밥 추가+1000원", en: "Add rice+1000원" },
        ] } },
    ],
  },
  {
    id: 6,
    name: { ko: "용용차이나", en: "YongYong China" },
    emoji: "🥡", time: "22~32", rating: 4.6, reviews: 1876, fee: 3000,
    category: { ko: "중식", en: "Chinese" },
    badge: { ko: "", en: "" },
    menus: [
      { id: "cn1",
        name: { ko: "짜장면", en: "Jjajangmyeon" },
        desc: { ko: "춘장 볶은 정통 짜장", en: "Classic black bean noodles" },
        price: 7500,
        options: { toppings: [
          { ko: "계란 추가+500원", en: "Add egg+500원" },
          { ko: "공기밥 추가+1000원", en: "Add rice+1000원" },
        ] } },
      { id: "cn2",
        name: { ko: "탕수육 (대)", en: "Sweet & Sour Pork (Large)" },
        desc: { ko: "바삭한 찹쌀 탕수육", en: "Crispy glutinous-rice batter" },
        price: 19000,
        options: { toppings: [
          { ko: "소스 곁들임+500원", en: "Sauce on the side+500원" },
        ] } },
      { id: "cn3",
        name: { ko: "짬뽕", en: "Spicy Seafood Noodles" },
        desc: { ko: "얼큰 해물 짬뽕", en: "Bold spicy seafood broth" },
        price: 8500,
        options: { spicy: true, toppings: [
          { ko: "해물 추가+2000원", en: "Extra seafood+2000원" },
        ] } },
    ],
  },
  {
    id: 7,
    name: { ko: "맵다매워 떡볶이", en: "Spicy-AF Tteokbokki" },
    emoji: "🧡", time: "12~20", rating: 4.5, reviews: 4521, fee: 1500,
    category: { ko: "분식", en: "Street Food" },
    badge: { ko: "최저배달비", en: "Cheap Delivery" },
    menus: [
      { id: "b1",
        name: { ko: "로제 떡볶이", en: "Rosé Tteokbokki" },
        desc: { ko: "크리미한 로제소스", en: "Creamy rosé sauce" },
        price: 7900,
        options: { spicy: true, size: true, toppings: [
          { ko: "치즈 추가+1000원", en: "Add cheese+1000원" },
          { ko: "라면사리 추가+500원", en: "Add ramen+500원" },
          { ko: "만두 추가+1500원", en: "Add dumplings+1500원" },
        ] } },
      { id: "b2",
        name: { ko: "참치김밥 2줄", en: "Tuna Kimbap (2 rolls)" },
        desc: { ko: "고소한 참치마요", en: "Savory tuna-mayo" },
        price: 5500, options: {} },
      { id: "b3",
        name: { ko: "모둠튀김", en: "Mixed Tempura" },
        desc: { ko: "김말이+고추+새우", en: "Seaweed roll, pepper, shrimp" },
        price: 4500,
        options: { toppings: [
          { ko: "새우튀김 추가+1000원", en: "Add fried shrimp+1000원" },
        ] } },
    ],
  },
  {
    id: 8,
    name: { ko: "카페 달콤 로스터리", en: "Cafe Dalkom Roastery" },
    emoji: "☕", time: "10~18", rating: 4.7, reviews: 2234, fee: 2500,
    category: { ko: "카페", en: "Cafe" },
    badge: { ko: "추천", en: "Recommended" },
    menus: [
      { id: "cf1",
        name: { ko: "아이스 아메리카노", en: "Iced Americano" },
        desc: { ko: "산미 적은 블렌드", en: "Low-acidity blend" },
        price: 4500,
        options: { size: true, toppings: [
          { ko: "샷 추가+500원", en: "Extra shot+500원" },
          { ko: "시럽 추가+300원", en: "Add syrup+300원" },
        ] } },
      { id: "cf2",
        name: { ko: "딸기 생크림 케이크", en: "Strawberry Cream Cake" },
        desc: { ko: "부드러운 시트 2단", en: "Two soft sponge layers" },
        price: 7800,
        options: { toppings: [
          { ko: "생크림 추가+500원", en: "Extra cream+500원" },
        ] } },
      { id: "cf3",
        name: { ko: "소금빵 2개", en: "Salt Bread (2pc)" },
        desc: { ko: "겉바속촉 버터풍미", en: "Crispy outside, buttery inside" },
        price: 5200, options: {} },
      { id: "cf4",
        name: { ko: "버터떡", en: "Butter Rice Cake" },
        desc: { ko: "고소한 버터가 듬뿍 찰떡", en: "Chewy rice cake with buttery richness" },
        price: 1300, options: {} },
    ],
  },
  {
    id: 9,
    name: { ko: "마라홍 마라탕", en: "MaraHong Mala Soup" },
    emoji: "🌶️", time: "20~30", rating: 4.6, reviews: 1654, fee: 2800,
    category: { ko: "마라탕", en: "Mala" },
    badge: { ko: "인기", en: "Popular" },
    menus: [
      { id: "ml1",
        name: { ko: "마라탕 (1인)", en: "Mala Soup (single)" },
        desc: { ko: "직접 고른 재료 조합", en: "Pick your own ingredients" },
        price: 12900,
        options: { spicy: true, toppings: [
          { ko: "당면 추가+500원", en: "Add glass noodles+500원" },
          { ko: "두부 추가+500원", en: "Add tofu+500원" },
          { ko: "새우 추가+2000원", en: "Add shrimp+2000원" },
        ] } },
      { id: "ml2",
        name: { ko: "마라샹궈", en: "Mala Xiangguo" },
        desc: { ko: "볶아서 더 진한 매운맛", en: "Stir-fried, deeper heat" },
        price: 15900,
        options: { spicy: true, toppings: [
          { ko: "당면 추가+500원", en: "Add glass noodles+500원" },
          { ko: "새우 추가+2000원", en: "Add shrimp+2000원" },
        ] } },
      { id: "ml3",
        name: { ko: "꿔바로우", en: "Guobaorou" },
        desc: { ko: "달콤바삭 중화 탕수육", en: "Sweet, crispy Chinese pork" },
        price: 13500, options: {} },
    ],
  },
  {
    id: 10,
    name: { ko: "딜리셔스 디저트", en: "Delicious Desserts" },
    emoji: "🍦", time: "8~15", rating: 4.8, reviews: 987, fee: 2000,
    category: { ko: "아이스크림", en: "Ice Cream" },
    badge: { ko: "신규", en: "New" },
    menus: [
      { id: "ic1",
        name: { ko: "파인트 아이스크림", en: "Pint Ice Cream" },
        desc: { ko: "맛 2가지 선택 가능", en: "Choose two flavors" },
        price: 8900,
        options: { toppings: [
          { ko: "초코칩 추가+500원", en: "Add choc chips+500원" },
          { ko: "스프링클 추가+300원", en: "Add sprinkles+300원" },
        ] } },
      { id: "ic2",
        name: { ko: "아이스크림 케이크", en: "Ice Cream Cake" },
        desc: { ko: "초코+바닐라 레이어", en: "Choc + vanilla layers" },
        price: 25900,
        options: { toppings: [
          { ko: "문구 작성+1000원", en: "Custom message+1000원" },
        ] } },
      { id: "ic3",
        name: { ko: "쿨 아이스티", en: "Cool Iced Tea" },
        desc: { ko: "복숭아 아이스티", en: "Peach iced tea" },
        price: 3500, options: { size: true } },
      { id: "ic4",
        name: { ko: "두바이 쫀득 쿠키", en: "Dubai Chewy Cookie" },
        desc: { ko: "피스타치오 필링 쫀득 쿠키", en: "Pistachio-filled chewy cookie" },
        price: 5900, options: {} },
    ],
  },
  {
    id: 11,
    name: { ko: "멋진 막창 예쁜 곱창", en: "Cool Tripe, Pretty Tripe" },
    emoji: "🫀", time: "25~35", rating: 4.8, reviews: 1342, fee: 2000,
    category: { ko: "곱창", en: "Tripe" },
    badge: { ko: "인기", en: "Popular" },
    menus: [
      { id: "gp1",
        name: { ko: "야채곱창", en: "Veggie Tripe Stir-Fry" },
        desc: { ko: "신선한 야채와 곱창 볶음", en: "Fresh veggies + tripe stir-fried" },
        price: 13900,
        options: { spicy: true, toppings: [
          { ko: "공기밥 추가+1000원", en: "Add rice+1000원" },
          { ko: "치즈 추가+1000원", en: "Add cheese+1000원" },
        ] } },
      { id: "gp2",
        name: { ko: "알곱창", en: "Roe Tripe" },
        desc: { ko: "탱글탱글 알이 가득한 곱창", en: "Tripe packed with roe" },
        price: 15900,
        options: { spicy: true, toppings: [
          { ko: "공기밥 추가+1000원", en: "Add rice+1000원" },
        ] } },
      { id: "gp3",
        name: { ko: "대구막창", en: "Daegu-style Tripe BBQ" },
        desc: { ko: "대구식 매콤달콤 막창구이", en: "Sweet-spicy Daegu BBQ" },
        price: 14900,
        options: { spicy: true, toppings: [
          { ko: "공기밥 추가+1000원", en: "Add rice+1000원" },
          { ko: "된장찌개 추가+2000원", en: "Add soybean stew+2000원" },
        ] } },
    ],
  },
  {
    id: 12,
    name: { ko: "스시히로 초밥집", en: "SushiHiro" },
    emoji: "🍣", time: "20~30", rating: 4.9, reviews: 2105, fee: 3000,
    category: { ko: "초밥", en: "Sushi" },
    badge: { ko: "추천", en: "Recommended" },
    menus: [
      { id: "su1",
        name: { ko: "모듬 초밥 10피스", en: "Assorted Sushi (10pc)" },
        desc: { ko: "연어·참치·광어 등 신선한 구성", en: "Salmon, tuna, flounder & more" },
        price: 18900,
        options: { toppings: [
          { ko: "와사비 추가+200원", en: "Extra wasabi+200원" },
          { ko: "간장 추가+200원", en: "Extra soy sauce+200원" },
        ] } },
      { id: "su2",
        name: { ko: "연어 초밥 6피스", en: "Salmon Sushi (6pc)" },
        desc: { ko: "두툼한 생연어 듬뿍", en: "Generous thick salmon slices" },
        price: 12900,
        options: { toppings: [
          { ko: "와사비 추가+200원", en: "Extra wasabi+200원" },
        ] } },
      { id: "su3",
        name: { ko: "참치 뱃살 초밥 4피스", en: "Otoro Sushi (4pc)" },
        desc: { ko: "부드럽고 고소한 오토로", en: "Buttery rich tuna belly" },
        price: 14900, options: {} },
      { id: "su4",
        name: { ko: "우동 세트", en: "Udon Set" },
        desc: { ko: "따뜻한 가케우동 + 초밥 3피스", en: "Warm kake udon + 3pc sushi" },
        price: 13500, options: { spicy: true } },
    ],
  },
  {
    id: 13,
    name: { ko: "엽땡떡볶이", en: "YeopDdaeng Tteokbokki" },
    emoji: "🌶️", time: "15~25", rating: 4.7, reviews: 3210, fee: 2000,
    category: { ko: "분식", en: "Street Food" },
    badge: { ko: "인기", en: "Popular" },
    menus: [
      { id: "yt1",
        name: { ko: "엽땡 떡볶이 (1인)", en: "YeopDdaeng Tteokbokki (single)" },
        desc: { ko: "중독성 있는 매콤달콤 소스", en: "Addictive sweet-spicy sauce" },
        price: 9900,
        options: { spicy: true, size: true, toppings: [
          { ko: "치즈 추가+1000원", en: "Add cheese+1000원" },
          { ko: "라면사리 추가+500원", en: "Add ramen+500원" },
          { ko: "만두 추가+1500원", en: "Add dumplings+1500원" },
        ] } },
      { id: "yt2",
        name: { ko: "로제 떡볶이 (1인)", en: "Rosé Tteokbokki (single)" },
        desc: { ko: "부드럽고 크리미한 로제", en: "Soft, creamy rosé" },
        price: 9900,
        options: { size: true, toppings: [
          { ko: "치즈 추가+1000원", en: "Add cheese+1000원" },
          { ko: "라면사리 추가+500원", en: "Add ramen+500원" },
        ] } },
      { id: "yt3",
        name: { ko: "순대 모둠", en: "Sundae Platter" },
        desc: { ko: "당면순대 + 떡볶이 소스", en: "Glass-noodle sundae + tteokbokki sauce" },
        price: 6500, options: { spicy: true } },
    ],
  },
  {
    id: 14,
    name: { ko: "버거팩토리", en: "Burger Factory" },
    emoji: "🍔", time: "20~30", rating: 4.8, reviews: 2418, fee: 2800,
    category: { ko: "햄버거", en: "Burger" },
    badge: { ko: "추천", en: "Recommended" },
    menus: [
      { id: "hb1",
        name: { ko: "시그니처 치즈버거", en: "Signature Cheeseburger" },
        desc: { ko: "두툼한 패티와 체다치즈", en: "Thick patty with cheddar" },
        price: 9800,
        options: { size: true, toppings: [
          { ko: "치즈 추가+1000원", en: "Add cheese+1000원" },
          { ko: "베이컨 추가+1500원", en: "Add bacon+1500원" },
          { ko: "감자튀김 추가+2500원", en: "Add fries+2500원" },
        ] } },
      { id: "hb2",
        name: { ko: "더블 베이컨 버거 세트", en: "Double Bacon Burger Set" },
        desc: { ko: "패티 2장 + 베이컨 + 감튀", en: "Two patties + bacon + fries" },
        price: 14800,
        options: { size: true, toppings: [
          { ko: "치즈 추가+1000원", en: "Add cheese+1000원" },
          { ko: "콜라 추가+1500원", en: "Add cola+1500원" },
        ] } },
      { id: "hb3",
        name: { ko: "크리스피 감자튀김", en: "Crispy Fries" },
        desc: { ko: "겉바속촉 클래식 프라이", en: "Classic crispy-tender fries" },
        price: 4200,
        options: { size: true, toppings: [
          { ko: "치즈시즈닝 추가+700원", en: "Add cheese seasoning+700원" },
        ] } },
    ],
  },
  {
    id: 15,
    name: { ko: "화덕피자랩", en: "Stone Oven Pizza Lab" },
    emoji: "🍕", time: "30~40", rating: 4.9, reviews: 1986, fee: 3500,
    category: { ko: "피자", en: "Pizza" },
    badge: { ko: "인기", en: "Popular" },
    menus: [
      { id: "piz1",
        name: { ko: "페퍼로니 피자", en: "Pepperoni Pizza" },
        desc: { ko: "짭짤한 페퍼로니 듬뿍", en: "Loaded with salty pepperoni" },
        price: 18900,
        options: { size: true, toppings: [
          { ko: "치즈 추가+2000원", en: "Add cheese+2000원" },
          { ko: "핫소스 추가+500원", en: "Add hot sauce+500원" },
          { ko: "갈릭디핑소스 추가+700원", en: "Add garlic dip+700원" },
        ] } },
      { id: "piz2",
        name: { ko: "불고기 피자", en: "Bulgogi Pizza" },
        desc: { ko: "달콤짭짤 불고기 토핑", en: "Sweet-savory bulgogi topping" },
        price: 20900,
        options: { size: true, toppings: [
          { ko: "치즈 추가+2000원", en: "Add cheese+2000원" },
          { ko: "콘샐러드 추가+1500원", en: "Add corn salad+1500원" },
          { ko: "갈릭디핑소스 추가+700원", en: "Add garlic dip+700원" },
        ] } },
      { id: "piz3",
        name: { ko: "치즈오븐스파게티", en: "Oven Cheese Spaghetti" },
        desc: { ko: "피자와 찰떡궁합 사이드", en: "Perfect pizza side" },
        price: 6900,
        options: { toppings: [
          { ko: "치즈 추가+1000원", en: "Add cheese+1000원" },
        ] } },
    ],
  },
  {
    id: 16,
    name: { ko: "문어대왕 타코야끼", en: "Octo-King Takoyaki" },
    emoji: "🐙", time: "15~25", rating: 4.7, reviews: 1243, fee: 2000,
    category: { ko: "타코야끼", en: "Takoyaki" },
    badge: { ko: "신규", en: "New" },
    menus: [
      { id: "tak1",
        name: { ko: "오리지널 타코야끼 6개", en: "Original Takoyaki (6pc)" },
        desc: { ko: "문어 가득 바삭한 겉면, 촉촉한 속살", en: "Crispy outside, soft inside, packed with octopus" },
        price: 9000,
        options: { toppings: [
          { ko: "마요네즈 추가+300원", en: "Add mayo+300원" },
          { ko: "가쓰오부시 추가+300원", en: "Add bonito flakes+300원" },
          { ko: "치즈소스 추가+700원", en: "Add cheese sauce+700원" },
        ] } },
      { id: "tak2",
        name: { ko: "치즈 타코야끼 8개", en: "Cheese Takoyaki (8pc)" },
        desc: { ko: "녹진한 모짜렐라 치즈가 쭉쭉", en: "Stretchy melted mozzarella" },
        price: 12000,
        options: { toppings: [
          { ko: "마요네즈 추가+300원", en: "Add mayo+300원" },
          { ko: "갈릭소스 추가+500원", en: "Add garlic sauce+500원" },
        ] } },
      { id: "tak3",
        name: { ko: "새우 타코야끼 6개", en: "Shrimp Takoyaki (6pc)" },
        desc: { ko: "탱글탱글 새우살이 통째로", en: "Bouncy whole shrimp inside" },
        price: 11000,
        options: { toppings: [
          { ko: "마요네즈 추가+300원", en: "Add mayo+300원" },
          { ko: "가쓰오부시 추가+300원", en: "Add bonito flakes+300원" },
        ] } },
      { id: "tak4",
        name: { ko: "타코야끼 + 쇼유라멘 세트", en: "Takoyaki + Shoyu Ramen Set" },
        desc: { ko: "오리지널 6개 + 간장라멘 한 그릇", en: "6 takoyaki + a bowl of soy ramen" },
        price: 17500,
        options: { spicy: true, toppings: [
          { ko: "차슈 추가+2000원", en: "Add chashu+2000원" },
          { ko: "반숙달걀 추가+1000원", en: "Add soft egg+1000원" },
        ] } },
    ],
  },
  {
    id: 17,
    name: { ko: "빙수나라 24시", en: "Bingsu World 24h" },
    emoji: "🍧", time: "10~18", rating: 4.8, reviews: 2134, fee: 1500,
    category: { ko: "빙수", en: "Bingsu" },
    badge: { ko: "인기", en: "Popular" },
    menus: [
      { id: "bs1",
        name: { ko: "딸기 설빙", en: "Strawberry Bingsu" },
        desc: { ko: "신선한 생딸기 듬뿍 올린 시그니처", en: "Loaded with fresh strawberries" },
        price: 11900,
        options: { size: true, toppings: [
          { ko: "딸기 추가+1500원", en: "Add strawberries+1500원" },
          { ko: "연유 추가+500원", en: "Add condensed milk+500원" },
          { ko: "아이스크림 추가+1000원", en: "Add ice cream+1000원" },
        ] } },
      { id: "bs2",
        name: { ko: "인절미 빙수", en: "Injeolmi Bingsu" },
        desc: { ko: "콩가루 듬뿍, 쫄깃한 찰떡 토핑", en: "Soybean powder + chewy rice cakes" },
        price: 10900,
        options: { size: true, toppings: [
          { ko: "찰떡 추가+800원", en: "Add rice cake+800원" },
          { ko: "연유 추가+500원", en: "Add condensed milk+500원" },
        ] } },
      { id: "bs3",
        name: { ko: "망고 빙수", en: "Mango Bingsu" },
        desc: { ko: "달콤한 생망고 시럽과 망고 큐브", en: "Sweet fresh mango syrup & cubes" },
        price: 12900,
        options: { size: true, toppings: [
          { ko: "망고 추가+2000원", en: "Add mango+2000원" },
          { ko: "코코넛젤리 추가+700원", en: "Add coconut jelly+700원" },
        ] } },
      { id: "bs4",
        name: { ko: "팥 빙수", en: "Red Bean Bingsu" },
        desc: { ko: "정통 국산 팥 빙수, 깊은 단맛", en: "Classic red bean — deeply sweet" },
        price: 9900,
        options: { size: true, toppings: [
          { ko: "팥 추가+1000원", en: "Add red bean+1000원" },
          { ko: "찰떡 추가+800원", en: "Add rice cake+800원" },
          { ko: "아이스크림 추가+1000원", en: "Add ice cream+1000원" },
        ] } },
    ],
  },
];
